# Generated by Django 4.1.13 on 2024-07-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_or_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fd_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fd_rating', models.CharField(max_length=100)),
                ('fd_feedback', models.CharField(max_length=100)),
                ('fd_given_to', models.CharField(max_length=100)),
                ('fd_status', models.IntegerField(default=0)),
                ('fd_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
